CREATE TABLE REGIONS
(
    REGION_ID NUMBER(6) NOT NULL PRIMARY KEY,
    REGION_NAME VARCHAR2(20)
);

CREATE TABLE COUNTRIES
(
    COUNTRY_ID NUMBER(6) NOT NULL PRIMARY KEY,
    COUNTRY_NAME VARCHAR2(20),
    REGION_ID NUMBER(6),
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)    
);

CREATE TABLE LOCATIONS
(
    LOCATION_ID NUMBER(6) NOT NULL PRIMARY KEY,
    STREET_ADDRESS VARCHAR2(30),
    POSTAL_CODE VARCHAR2(20),
    CITY VARCHAR2(20),
    STATE_PROVINCE VARCHAR2(30),
    COUNTRY_ID NUMBER(6) NOT NULL,
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
);

CREATE TABLE JOBS
(
    JOB_ID NUMBER(6) NOT NULL PRIMARY KEY,
    JOB_TITLE VARCHAR2(20),
    MIN_SALARY NUMBER(8,2),
    MAX_SALARY NUMBER(8,2)
);

CREATE TABLE DEPARTMENTS 
(
    DEPARTMENT_ID NUMBER(6) NOT NULL PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(6),
    MANAGER_ID NUMBER(6),
    LOCATION_ID NUMBER(6),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID NUMBER(6) NOT NULL PRIMARY KEY,
    MANAGER_ID NUMBER(6),
    DEPARTMENT_ID NUMBER(6),
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(25) NOT NULL,
    EMAIL VARCHAR2(25) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID NUMBER(6) NOT NULL,
    SALARY NUMBER(8,2),
    COMMISSION_PCT NUMBER(2,2),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
);

CREATE TABLE JOB_HISTORY
(
    EMPLOYEE_ID NUMBER(6),
    START_DATE DATE,
    END_DATE DATE,
    JOB_ID NUMBER(6),
    DEPARTMENT_ID NUMBER(6),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);
