-- QUESTÃO 1
CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID NUMBER(6) NOT NULL PRIMARY KEY,
    MANAGER_ID NUMBER(6),
    DEPARTMENT_ID NUMBER(6),
    FIRST_NAME VARCHAR2(20),
    LAST_NAME VARCHAR2(25) NOT NULL,
    EMAIL VARCHAR2(25) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID NUMBER(6) NOT NULL,
    SALARY NUMBER(8,2),
    COMMISSION_PCT NUMBER(2,2),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID)
)

-- QUESTÃO 2
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, MANAGER_ID, SALARY 
FROM EMPLOYEES 
WHERE JOB_ID IN (SELECT JOB_ID FROM JOBS WHERE JOB_TITLE = 'Marketing Manager');

-- QUESTÃO 3
SELECT 
    E.EMPLOYEE_ID, 
    E.FIRST_NAME AS Employee_First_Name, 
    M.FIRST_NAME AS Manager_First_Name, 
    D.DEPARTMENT_NAME, 
    L.STREET_ADDRESS
FROM 
    EMPLOYEES E, 
    DEPARTMENTS D, 
    LOCATIONS L,
    EMPLOYEES M
WHERE 
    E.DEPARTMENT_ID = D.DEPARTMENT_ID AND
    D.LOCATION_ID = L.LOCATION_ID AND
    E.MANAGER_ID = M.EMPLOYEE_ID
    AND E.DEPARTMENT_ID = 50;

-- QUESTION 4
Exibir employee_id, last_name, department_id, manager_id e salary de todos os funcionários cujo salário encontra-se entre 2000.00 e 10000.00 inclusive.
SELECT EMPLOYEE_ID, LAST_NAME, DEPARTMENT_ID,MANAGER_ID, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 2000 AND 10000

-- QUESTION 5
Questão 5: (0,5 ponto)
Excluir todos os funcionários cujo salário faça parte da lista 1000, 1500 e 3000 e cujo primeiro nome comece com a letra K.
DELETE FROM EMPLOYEES
WHERE SALARY IN (1000, 1500, 3000)
AND FIRST_NAME LIKE 'K%';

-- QUESTION 6
Questão 6: (0,5 ponto)
Exibir a soma, a média, o maior e o menor salário dos funcionários do departamento 50.

SELECT 
    SUM(SALARY) AS Total_Salary,
    AVG(SALARY) AS Average_Salary,
    MAX(SALARY) AS Max_Salary,
    MIN(SALARY) AS Min_Salary
FROM 
    EMPLOYEES
WHERE 
    DEPARTMENT_ID = 50;
